require('seneca')()
  .use('./lib/microservices/htmler')
  .listen({type: 'tcp', port: 18910})
  .use('./lib/microservices/xmler')
  .listen(8765)
  .client({type: 'tcp', port: 18910})
  .act('role:convert-html,cmd:to', (_, msg) => console.log(msg))
  .client(8765)
  .act('role:convert-xml,cmd:to', (_, msg) => console.log(msg))
