require('seneca')()
  .use('./lib/microservices/htmler')
  .listen(8910)
  .use('./lib/microservices/xmler')
  .listen(8765)
  .client(8910)
  .act('role:convert,cmd:to', (_, msg) => console.log(msg))
  .client(8765)
  .act('role:convert,cmd:to', (_, msg) => console.log(msg))
